[project]
name = "salespilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "langgraph>=1.2.11",
    "openai>=3.3.1",
    "psycopg[binary]>=3.3.4",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
salespilot = "salespilot:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
